# Packages to be installed
# 1. GIT
# 2. .NET7 SDK

# The base image
FROM alpine:latest

# Upgrade the core packages
RUN apk update \
	&& apk upgrade --no-cache

# Install dotnet6-runtime package 
RUN apk add --no-cache dotnet6-sdk

# Install other common required packages
RUN apk add --no-cache git
